# Generated by Django 4.2.4 on 2023-11-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wheat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_harvest', models.DateField()),
                ('Uid', models.TextField()),
                ('Section', models.IntegerField()),
                ('Temp', models.FloatField()),
                ('Pressure', models.FloatField()),
                ('Weight', models.FloatField()),
                ('CO2', models.FloatField()),
                ('Price', models.FloatField()),
                ('Est_date_of_exp', models.DateField()),
            ],
        ),
    ]
