# Generated by Django 4.2.4 on 2023-11-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheat',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
