# Generated by Django 4.0.6 on 2023-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crops', '0002_alter_wheat_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheat',
            name='Date_of_harvest',
        ),
        migrations.RemoveField(
            model_name='wheat',
            name='Est_date_of_exp',
        ),
        migrations.RemoveField(
            model_name='wheat',
            name='Pressure',
        ),
        migrations.RemoveField(
            model_name='wheat',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='wheat',
            name='Section',
        ),
        migrations.AddField(
            model_name='wheat',
            name='Ethylene',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wheat',
            name='Humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wheat',
            name='Light_Value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wheat',
            name='O2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wheat',
            name='CO2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wheat',
            name='Temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wheat',
            name='Weight',
            field=models.FloatField(null=True),
        ),
    ]
