# Generated by Django 4.0.6 on 2023-11-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crops', '0003_remove_wheat_date_of_harvest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheat',
            name='Food_Type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
