# Generated by Django 4.0.6 on 2023-11-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crops', '0004_wheat_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheat',
            name='Food_Type',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
