# Generated by Django 4.0.6 on 2023-11-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crops', '0005_alter_wheat_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheat',
            name='Food_Type',
        ),
    ]
