# Generated by Django 4.0.6 on 2023-11-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crops', '0006_remove_wheat_food_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wheat',
            new_name='Item',
        ),
    ]
